"""initial

Revision ID: 37a2bc09fc8b
Revises:
Create Date: 2025-05-18 21:29:52.145863

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '37a2bc09fc8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correspondence_user',
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('active_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_staff', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('is_superuser', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('messages_sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_received_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['correspondence_user.id'], name=op.f('correspondence_user_manager_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('correspondence_user_pkey'))
    )
    op.create_table('correspondence_organization',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['correspondence_user.id'], name=op.f('correspondence_organization_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('correspondence_organization_pkey'))
    )
    op.create_table('correspondence_conversation',
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('unread', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['correspondence_organization.id'], name=op.f('correspondence_conversation_organization_id_fkey')),
    sa.ForeignKeyConstraint(['receiver_id'], ['correspondence_user.id'], name=op.f('correspondence_conversation_receiver_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('correspondence_conversation_pkey'))
    )
    op.create_table('correspondence_message',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['correspondence_conversation.id'], name=op.f('correspondence_message_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['correspondence_user.id'], name=op.f('correspondence_message_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('correspondence_message_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correspondence_message')
    op.drop_table('correspondence_conversation')
    op.drop_table('correspondence_organization')
    op.drop_table('correspondence_user')
    # ### end Alembic commands ###
